### ISSUE TITLE
Wrong option to button class ('prompt and other')

### ISSUE THREAD

**Issue by tmendesilva** [kartik-v/yii2-dialog#18]
I found a problem on documentation. To set button class on types Dialog::DIALOG_PROMPT and Dialog::DIALOG_OTHER the correct option is 'cssClass', not 'class' (saw on Boostrap Dialog plugin options)

**Comment by kartik-v** [comment]
Resolved via [updates to release v1.0.2](https://github.com/kartik-v/yii2-dialog/commit/d8daf8c9c6c0dcf66b44ede92fa437d243f74ef2).
