### ISSUE TITLE
 Problems installing kartik - v / dialog

### ISSUE THREAD

**Issue by yolberjp** [kartik-v/yii2-dialog#2]
When trying to install kartik - v / dialog following the instructions , I throws an error:

 Problem 1
    - kartik-v/yii2-dialog v1.0.0 requires bower-asset/bootstrap3-dialog ~1.34 -> no matching package found.
    - kartik-v/yii2-dialog 1.0.x-dev requires bower-asset/bootstrap3-dialog ~1.34 -> no matching package found.
    - kartik-v/yii2-dialog dev-master requires bower-asset/bootstrap3-dialog ~1.34 -> no matching package found.
    - Installation request for kartik-v/yii2-dialog @dev -> satisfiable by kartik-v/yii2-dialog[dev-master, 1.0.x-dev, v1.0.0].

I tried to install bootstrap3 -dialog on the path: "vendor/bower-assets" but still does not work. Can you help me? I need this tool , thanks

**Comment by yolberjp** [comment]
@kartik-v  I need your help please :(

**Comment by kartik-v** [comment]
Check if you have a valid yii install via composer with all its package dependencies.

You may need to look at your application composer.json settings and read composer docs to understand how to set app dependencies. You may [also want to check if this webtip helps you](http://webtips.krajee.com/setting-composer-minimum-stability-application/). 

Unfortunately cannot help much as you may need to debug your install. Typically these things work without issues if your yii install is correct (this includes the basic composer and bower setups) and composer is setup fine.

**Comment by yolberjp** [comment]
I have tried many ways that abut on the internet to solve the problem but still can not get solved.  Cualquier otro widget me funciona a la perfeccion, es este el que genera problemas

**Comment by nadirvishun** [comment]
I also have this problem,the error message are same  to you ,and I also do as "Setting composer minimum stability for your application",but not work.
update：@yolberjp
2016/04/07，I use “composer self-update” again，then it worked. 
But I used this  command several days ago，at that time it not work .
So I do not know the real reason.

**Comment by yolberjp** [comment]
I continued researching and I have not found anything concrete . I do not want end up improvising with native javascript and bootstrap. @kartik-v  do you think there is something we are going through we overlooked?

**Comment by kartik-v** [comment]
Try setting up a new yii basic app from scratch and try to install this extension and let know.

You do not seem to have the pre-requisites right in your yii install. The bower asset is not being loaded (you may want to check if you have composer asset plugin installed for loading bower dependencies).

**Comment by nadirvishun** [comment]
@yolberjp ,you can also try "BootboxJS",do like this [wiki](http://www.yiiframework.com/wiki/654/escape-from-default-s-yii2-delete-confirm-box/),or in packagist search "yii2 bootbox".the usage like this.

**Comment by yolberjp** [comment]
Ya encontré la solución. El problema en mi caso es que había instalado Yii2 desde composer pero no el plugin de Asset. Este es el comando que me sirvió y luego de correrlo no tuve problemas para instalar cualquier otra extensión de kartik 

$ composer global require "fxp/composer-asset-plugin:~1.1.1"

**Comment by bicsi64** [comment]
Yes, thanks yolberjp, that's all (actually: $ composer global require "fxp/composer-asset-plugin:^1.2.0")
