### ISSUE TITLE
bower-asset/bootstrap3-dialog reuired

### ISSUE THREAD

**Issue by chameeracd** [kartik-v/yii2-dialog#27]
composer require kartik-v/yii2-dialog

gives following error -

Using version ^1.0 for kartik-v/yii2-dialog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - kartik-v/yii2-dialog v1.0.1 requires bower-asset/bootstrap3-dialog ~1.34 -> no matching package found.
    - kartik-v/yii2-dialog v1.0.0 requires bower-asset/bootstrap3-dialog ~1.34 -> no matching package found.
    - Installation request for kartik-v/yii2-dialog ^1.0 -> satisfiable by kartik-v/yii2-dialog[v1.0.0, v1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

i already installed fxp/composer-asset-plugin (v1.4.1)

**Comment by kartik-v** [comment]
Not sure if this can be reproduced. Note that Yii latest releases do not require fxp/composer-asset-plugin. Please retry with a fresh app install and reinstall this extension and compare with your application install.

**Comment by chameeracd** [comment]
sorry, my bad. its due to proxy; all the dependancies are updated, composer diagnose also ok. but few  assets are not working. everything is fine after removing proxy server. sorry for troubling you...
