### ISSUE TITLE
Add feature to override Yii `data-confirm` dialog

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-dialog#28]
New boolean property `Dialog::overrideYiiConfirm` which defaults to `true`. Setting this to `true` will override all Yii confirmation dialogs with Krajee Dialog.

**Comment by kartik-v** [comment]
Resolved via [updates to release v1.0.2](https://github.com/kartik-v/yii2-dialog/commit/d8daf8c9c6c0dcf66b44ede92fa437d243f74ef2).

**Comment by attybean** [comment]
How should this property be set? 
I have tried either : `\Yii::$container->set('kartik\dialog\Dialog', ['overrideYiiConfirm' => false]); `or 
`\Yii::$container->set('kartik\dialog\Dialog', ['useNative' => true]);` in base controller and they both work. What is the best practice? Can it be set in the config files? It is an extension, but documentation on modification of extensions in config files is not easy to find. Thank you for all your excellent work. @kartik-v

**Comment by kartik-v** [comment]
Yes you need to do that way if you need to override the widget defaults. You can use either of the settings depending on what you need (useNative will always render the native browser dialog - while overrideYiiConfirm will just set it for the data-confirm behavior of yii).

But the recommended way to set this specific widget is to initialize the Dialog widget in your global view layout file that will be applied for all the views where you are using the specific layout. 

You can then trigger the dialogs via javascript using the dialogLib `krajeeDialog`.
