### ISSUE TITLE
Problem overwriting the default alert message when Kartik GridView is present

### ISSUE THREAD

**Issue by joepages** [kartik-v/yii2-dialog#38]
Hi there! 

I have followed all the process in order to replace Yii2 default alert with SweetAlert. The problem is that SweetAlert is only working properly whereKartik GridView is not present. 

GridView assets is replacing the yii.confirm js function... I have found a similar issue but the solution is not working for me... Is it there a way to disable this functionality trough the config/main ?

I'm trying to use this inside backend/config/main: 

```
'assetManager' => [
            'bundles' => [
                'kartik\dialog\Dialog' => [
                    'overrideYiiConfirm' => false,
                    'useNative' => true
                ],
            ],
        ],
```

the response is: 

where  gridview is: 
![Screen Shot 2019-08-20 at 9 24 33 AM](https://user-images.githubusercontent.com/583979/63350979-64491800-c32c-11e9-9b4c-4e64488fb5f5.png)

and where gridview is missing (how it should work): 
![Screen Shot 2019-08-20 at 9 24 45 AM](https://user-images.githubusercontent.com/583979/63350999-6dd28000-c32c-11e9-9a4a-8a302872e3ff.png)

Thanks!

**Comment by kartik-v** [comment]
The `overrideYiiConfirm` is a property of Dialog widget.... you are wrongly trying to set this within `assetManager` component in bundles... you need to rather set this in dependency injection `container` in your yii2 app config - cross check the [yii2 docs](https://www.yiiframework.com/doc/guide/2.0/en/concept-configurations)

**Comment by joepages** [comment]
I'm going to leave this here in case someone wants more specifics in how to solve this issue... 

I just created an extended GridView class where I customize my gridView and just added this code in order to override and use sweet alert assets.. 

```public $krajeeDialogSettings = [
        'useNative' => true,
        'overrideYiiConfirm' => false,
    ];```

**Comment by kartik-v** [comment]
Yes you need to set above actually within GridView::krajeeDialogSettings
