### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by panchenkodv** [kartik-v/yii2-dialog#4]
Hi! I've got some error on Ukrainian language page. How can I fix it?

yii\i18n\PhpMessageSource::loadFallbackMessages
The message file for category 'kvdialog' does not exist: /var/www/krasota-style.yii2/vendor/kartik-v/yii2-dialog/messages/uk-UA/kvdialog.php
Fallback file does not exist as well: /var/www/krasota-style.yii2/vendor/kartik-v/yii2-dialog/messages/uk/kvdialog.php

**Comment by kartik-v** [comment]
Create a pull request for your translation and follow contribution [guidelines ](https://github.com/kartik-v/yii2-dialog/issues/new). You can generate your translation messages template using yii message command (there is a config.php provided in messages folder).
